global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'gql-api'
    static_configs:
      - targets: ['gql-api:2112']

  - job_name: 'content-service'
    static_configs:
      - targets: [ 'content-service:9090' ]

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
